# Generated by Django 5.0.6 on 2024-05-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='todos', to='api.tag'),
        ),
    ]
